include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "build-aux/com.github.bilelmoussaoui.Authenticator.json"
        FLATPAK_MODULE: "Authenticator"
        MESON_ARGS: "-Dprofile=development"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "com.github.bilelmoussaoui.AuthenticatorDevel"
        BUNDLE: "authenticator-dev.flatpak"
    extends: .flatpak

flake8:
  stage: ".pre"
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E402,W503,E501 --show-source src/ --exclude __init__.py
