stages:
  - check
  - test

flatpak:
  image: "quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master"
  stage: test
  tags:
    - flatpak
  variables:
    BUNDLE: "authenticator-nightly.flatpak"
    MANIFEST_PATH: "build-aux/com.belmoussaoui.Authenticator.Devel.json"
    FLATPAK_MODULE: "authenticator"
    APP_ID: "com.belmoussaoui.Authenticator.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  script:
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --keep-build-dirs --user --disable-rofiles-fuse flatpak_app --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${APP_ID} ${BRANCH}
    - tar cf repo.tar repo/
  artifacts:
    name: 'Flatpak artifacts'
    expose_as: 'Get Flatpak bundle here'
    when: 'always'
    paths:
      - "${BUNDLE}"
      - '.flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-logs/meson-log.txt'
      - '.flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-logs/testlog.txt'
      - 'repo.tar'
    expire_in: 14 days

pages:
  image: "quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master"
  variables:
    MANIFEST_PATH: "build-aux/com.belmoussaoui.Authenticator.Devel.json"
    FLATPAK_MODULE: "authenticator"
  tags:
    - flatpak
  script:
    #- tar xf repo.tar
    - flatpak-builder --keep-build-dirs --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} flatpak_docs --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - echo "ninja src/doc" | flatpak-builder --force-clean --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_docs ${MANIFEST_PATH}
    - mv .flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/src/doc public
    - chmod -R a=rwx public
  artifacts:
    paths:
      - 'public'
  only:
    refs:
      - master

rustfmt:
  image: "rust:slim"
  stage: check
  script:
    - rustup component add rustfmt
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check

