[package]
name = "authenticator"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
gettext-rs= { version = "0.5", features = ["gettext-system"] }
pretty_env_logger = "0.4"
lazy_static = "1.4"
anyhow = "1.0"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = {  version = "1.4" , features = ["sqlite"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
nanoid = "0.3"
reqwest = "0.10"
url = "2.1"
gtk-macros = "0.2"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4"
package = "gtk4"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk4"
package = "gdk4"

[dependencies.libhandy]
git = "https://gitlab.gnome.org/bilelmoussaoui/libhandy4-rs"
package = "libhandy4"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"

