[package]
edition = "2021"
name = "authenticator"
version = "0.1.0"

[dependencies]
adw = {package = "libadwaita", version = "0.1.0"}
anyhow = "1.0"
ashpd = {version = "0.3", features = ["feature_pipewire", "feature_gtk4"]}
binascii = "0.1"
diesel = {version = "1.4", features = ["sqlite", "r2d2"]}
diesel_migrations = {version = "1.4", features = ["sqlite"]}
futures = "0.3"
gettext-rs = {version = "0.7", features = ["gettext-system"]}
gst = {package = "gstreamer", version = "0.18"}
gst4gtk = { package = "gst-plugin-gtk4", version = "0.1"}
gtk = {package = "gtk4", version = "0.4"}
gtk-macros = "0.3"
search-provider = "0.3"
hex = { version = "0.4.3", features = [ "serde" ] }
image = "0.24"
log = "0.4"
once_cell = "1.9"
percent-encoding = "2.1"
pretty_env_logger = "0.4"
qrcode = {version = "0.12", features = ["image"]}
quick-xml = "0.22"
rand = "0.8"
ring = "0.16"
rust-argon2 = "1.0"
secret-service = "2.0"
serde = "1.0"
serde_json = "1.0"
reqwest =  "0.11"
tokio = { version = "1.0", features = ["rt-multi-thread", "fs", "io-util"] }
unicase = "2.6"
url = "2.2"
zbar-rust = "0.0"
svg_metadata = "0.4"
scrypt = { version = "0.10", default-features = false }
aes-gcm = "0.9.4"
base64 = "0.13.0"
uuid = { version = "0.8", features = ["v4"] }
