[package]
name = "authenticator"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = { version = "0.7", features = ["v3_22"] }
libhandy = "0.4"
glib = { version = "0.8", features = ["subclassing"] }
gio = { version = "0.7", features = ["v2_46"] }
gdk = "0.11"
gdk-sys = "0.9"
gobject-sys = "0.9"
glib-sys = "0.9"
cairo-rs = "0.7"
pango = "0.7"
log = "0.4"
gdk-pixbuf = {version = "0.7", features = ["v2_32"] }
gettext-rs= { version = "0.4", features = ["gettext-system"] }
pretty_env_logger = "0.3"
lazy_static = "1.3"
failure = "0.1"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = {  version = "1.4" , features = ["sqlite"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
nanoid = "0.1"
reqwest = "0.9"
url = "2.1"
