[package]
edition = "2018"
name = "authenticator"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
ashpd =  { git = "https://github.com/bilelmoussaoui/ashpd", features=["feature_gtk4"] }
data-encoding = "2.1"
diesel = {version = "1.4", features = ["sqlite", "r2d2"]}
diesel_migrations = {version = "1.4", features = ["sqlite"]}
futures = "0.3"
gettext-rs = {version = "0.5", features = ["gettext-system"]}
gtk-macros = "0.2"
image = "0.23"
log = "0.4"
pretty_env_logger = "0.4"
quick-xml = "0.20"
surf = "2.1"
url = "2.2"
percent-encoding = "2.1"
zbar-rust = "0.0"
secret-service = "1.1"
once_cell = "1.5"
unicase = "2.6"
sha2 = "0.9"
hex = "0.4"
ring = "0.16"
serde = "1.0"
serde_json = "1.0"
qrcode = {version ="0.12",features=["image"]}
gtk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4"}
libadwaita = { git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs" }
async-std = "1.8"
